import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { resolve } from 'node:path';
// @ts-expect-error — plain ESM helper shared with the build scripts.
import { PAGES, NOT_FOUND } from './scripts/pages.mjs';

// Multi-page (MPA) build for GitHub Pages: every page in scripts/pages.mjs
// is a real, crawlable .html URL under the repo base path. The HTML entry
// files themselves are generated by scripts/gen-html.mjs.
const pageInput = Object.fromEntries(
  [...PAGES, NOT_FOUND].map((p: { key: string; file: string }) => [p.key, resolve(__dirname, p.file)]),
);

export default defineConfig({
  plugins: [react()],
  // Base path for GitHub Pages deployment (repo name).
  base: '/VoyagerTracker/',
  define: {
    // Date of the build; shown as "site last updated" and used in sitemap/JSON-LD.
    __BUILD_DATE__: JSON.stringify(new Date().toISOString().slice(0, 10)),
  },
  server: {
    port: 5173,
    open: false,
  },
  build: {
    rollupOptions: {
      input: pageInput,
    },
  },
});
