/**
 * gen-html.mjs — writes one Vite HTML entry file per page from pages.mjs.
 *
 * Each file carries its own title, description, canonical URL, Open Graph
 * and Twitter tags. Body content and JSON-LD are injected after the build
 * by prerender.mjs.
 *
 * Usage:  node scripts/gen-html.mjs   (runs automatically in `npm run build`)
 */

import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { PAGES, NOT_FOUND, SITE_NAME, pageHref } from './pages.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const esc = (s) => s.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');

function headMeta(p) {
  if (p.noindex) return '<meta name="robots" content="noindex" />';
  const url = pageHref(p);
  return [
    `<link rel="canonical" href="${url}" />`,
    '<meta name="robots" content="index, follow, max-image-preview:large" />',
    `<meta property="og:type" content="${p.schema === 'Article' ? 'article' : 'website'}" />`,
    `<meta property="og:site_name" content="${SITE_NAME}" />`,
    `<meta property="og:title" content="${esc(p.title)}" />`,
    `<meta property="og:description" content="${esc(p.description)}" />`,
    `<meta property="og:url" content="${url}" />`,
    '<meta property="og:locale" content="en_US" />',
    '<meta name="twitter:card" content="summary" />',
    `<meta name="twitter:title" content="${esc(p.title)}" />`,
    `<meta name="twitter:description" content="${esc(p.description)}" />`,
  ].join('\n    ');
}

for (const p of [...PAGES, NOT_FOUND]) {
  const html = `<!doctype html>
<!-- Generated by scripts/gen-html.mjs from scripts/pages.mjs — edit those, not this file. -->
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${esc(p.title)}</title>
    <meta name="description" content="${esc(p.description)}" />
    ${headMeta(p)}
    <meta name="theme-color" content="#020617" />
    <link rel="icon" type="image/svg+xml" href="/VoyagerTracker/favicon.svg" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;700&family=Noto+Sans+TC:wght@400;500;700;900&display=swap"
      rel="stylesheet"
    />
    <!--jsonld-->
  </head>
  <body>
    <div id="root" data-page="${p.key}"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`;
  writeFileSync(resolve(ROOT, p.file), html);
}
console.log(`gen-html: wrote ${PAGES.length + 1} HTML entry files.`);
