/**
 * validate-model.ts — compare the tracker model against JPL Horizons.
 *
 * Reads scripts/validation.generated.json (geocentric range every 5 days,
 * 2024–2031, written by fetch-horizons.mjs) and reports how far the
 * browser model drifts from JPL's ephemeris.
 *
 * Usage:  npm run validate
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { AU_KM, estimate, whenEarthDistanceReaches, type CraftId } from '../src/lib/ephemeris';

const data = JSON.parse(readFileSync('scripts/validation.generated.json', 'utf8')) as Record<
  CraftId,
  { jd: number; rangeKm: number; rangeRateKmS: number }[]
>;

const TDB_MINUS_UTC_MS = 69_184;
let failed = false;
const summary: Record<string, { year: number; maxErrKm: number }[]> = {};

for (const id of ['voyager1', 'voyager2'] as CraftId[]) {
  const rows: { year: number; err: number; rrErr: number }[] = data[id].map((row) => {
    const utcMs = (row.jd - 2_440_587.5) * 86_400_000 - TDB_MINUS_UTC_MS;
    const est = estimate(id, utcMs);
    return {
      year: new Date(utcMs).getUTCFullYear(),
      err: est.earthKm - row.rangeKm,
      rrErr: est.rangeRateKmS - row.rangeRateKmS,
    };
  });
  const byYear = new Map<number, { maxErr: number; maxRr: number }>();
  for (const r of rows) {
    if (r.year < 2024 || r.year > 2031) continue; // partial years at the ends
    const cur = byYear.get(r.year) ?? { maxErr: 0, maxRr: 0 };
    cur.maxErr = Math.max(cur.maxErr, Math.abs(r.err));
    cur.maxRr = Math.max(cur.maxRr, Math.abs(r.rrErr));
    byYear.set(r.year, cur);
  }
  console.log(`\n${id}: max |model − JPL| geocentric range by year`);
  for (const [year, v] of byYear) {
    console.log(
      `  ${year}: ${Math.round(v.maxErr).toLocaleString('en-US').padStart(9)} km  (${(v.maxErr / AU_KM).toFixed(6)} AU)   range-rate ±${v.maxRr.toFixed(3)} km/s`,
    );
  }
  summary[id] = [...byYear].map(([year, v]) => ({ year, maxErrKm: Math.round(v.maxErr) }));
  // Acceptance: within 100,000 km (< 0.001 AU) for 2025–2028.
  const worst = Math.max(...rows.filter((r) => r.year >= 2025 && r.year <= 2028).map((r) => Math.abs(r.err)));
  if (worst > 100_000) {
    console.error(`  FAIL: ${id} worst 2025–2028 error ${Math.round(worst)} km`);
    failed = true;
  }
}

// Milestone cross-check: NASA says Voyager 1 reaches one light-day on 2026-11-18.
const LIGHT_DAY_KM = 299_792.458 * 86_400;
const t = whenEarthDistanceReaches('voyager1', LIGHT_DAY_KM, Date.parse('2026-01-01T00:00:00Z'));
console.log(`\nModel: Voyager 1 reaches one light-day from Earth on ${t ? new Date(t).toISOString() : 'n/a'}`);

if (failed) process.exit(1);

writeFileSync(
  'src/data/validation-summary.generated.ts',
  `/** AUTO-GENERATED by scripts/validate-model.ts — model vs JPL Horizons geocentric range. */
export const VALIDATED_ON = '${new Date().toISOString().slice(0, 10)}';
export const LIGHT_DAY_MODEL_ISO = '${t ? new Date(t).toISOString() : ''}';
export const VALIDATION: Record<'voyager1' | 'voyager2', { year: number; maxErrKm: number }[]> = ${JSON.stringify(summary)};
`,
);
console.log('\nValidation passed.');
